### ISSUE TITLE
Retrieving an Object themeDisplay

### ISSUE THREAD

**Issue by BaranovNikita** [liferay/portletmvc4spring#10]
Hello! How can I get a theme object in my rest Spring controller? HttpServletRequest does not have this attribute

**Comment by ngriffin7a** [comment]
@BaranovNikita Assuming you are referring to the `ThemeDisplay` object, what methods on that object do you need to invoke? For example, do you need to call `themeDisplay.getScopeGroupId()` or something like that?

Since your REST controller is responding to requests that are bypassing the portlet container, you are dealing with an `HttpServletRequest` rather than a `PortletRequest`. So to further clarify my question, what "portlet" or "theme" related info does your REST endpoint need? And what will it do with that information?

**Comment by BaranovNikita** [comment]
> @BaranovNikita Assuming you are referring to the `ThemeDisplay` object, what methods on that object do you need to invoke? For example, do you need to call `themeDisplay.getScopeGroupId()` or something like that?
> 
> Since your REST controller is responding to requests that are bypassing the portlet container, you are dealing with an `HttpServletRequest` rather than a `PortletRequest`. So to further clarify my question, what "portlet" or "theme" related info does your REST endpoint need? And what will it do with that information?

Thanks. I want to get a sitemap through SitemapUtil, but all methods require a ThemeDisplay an argument

**Comment by ngriffin7a** [comment]
@BaranovNikita I recommend that you read this blog:
https://blogs.aca-it.be/liferay-themedisplay-angular-apps/

In particular, I recommend that you look at the Java source of the `convertThemeDisplay` method mentioned in the blog. I think that passing the relevant `ThemeDisplay` attributes in the request via JSON most closely approximates what you are trying to do here with your Spring REST controller.

Another way to accomplish this would be to use a portlet ResourceURL to invoke a PortletMVC4Spring controller method annotated with @ResourceMapping. That would cause the request to be a `javax.portlet.ResourceRequest` which participates in the portlet lifecycle, and Liferay would automatically provide the `ThemeDisplay` request attribute.

Please let me know if this answers your question. If so, we can close this issue. Thanks.

**Comment by BaranovNikita** [comment]
First way is nice. Thanks!
